language: android
install: sh install_license.sh
android:
  components:
    - build-tools-26.0.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - android-N